name: menu
description: menu with flutter,
  just wrap your widget ,and long tap to show menu
version: 0.1.4

author: Caijinglong<cjl_spy@163.com>
homepage: https://github.com/CaiJingLong/flutter_long_tap_menu

environment:
  sdk: '>=2.2.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
